### ISSUE TITLE
DNS server down

### ISSUE THREAD

**Issue by atomical** [OpenGems/rails_email_checker#3]
I see a rescued exception:

https://github.com/OpenGems/rails_email_checker/blob/master/lib/rails_email_checker/address.rb#L56-L63

In this case the e-mail is invalid? Such as in the case the DNS server is down.

**Comment by BorisBresciani** [comment]
@atomical Absolutely if the server is down, it will return `nil`, so if the `recorded` option is specified and it is `nil`, it will be an invalid email
